import { HtmlElement } from './../../nodes/HtmlElement';
import { PlainText } from './../../nodes/PlainText';
import { BlockQuote } from './../../nodes/BlockQuote';
import { DeepCoreNode } from './../../nodes';
import { DoNotEditComment } from '../../nodes/DoNotEditComment';
import { MarkdownOutput } from './MarkdownOutput';
import { addChildrenC } from '../../nodes/abstract/ContainerBase';

export function writeDoNotEditComment(
    _doNotEditComment: DoNotEditComment,
    output: MarkdownOutput,
    writeDeepCoreNode: (node: DeepCoreNode, output: MarkdownOutput) => void,
): void {
    writeDeepCoreNode(
        addChildrenC<DeepCoreNode, BlockQuote<DeepCoreNode>>(
            BlockQuote(),
            PlainText({
                text: 'This file is automatically generated by a build script.',
            }),
            HtmlElement({ tagName: 'br' }),
            PlainText({
                text:
                    'If you notice anything off, please feel free to open a new issue!',
            }),
        ),
        output,
    );
}
