import { BlockQuoteNode } from '../../nodes/BlockQuote';
import { DoNotEditCommentBase } from '../../nodes/DoNotEditComment';
import { HtmlElementNode } from '../../nodes/HtmlElement';
import { PlainTextNode } from '../../nodes/PlainText';
import { MarkdownOutput } from './MarkdownOutput';
import { writeDeepCoreNode, ParamWriteCoreNode } from '.';

export function writeDoNotEditComment(
    _doNotEditComment: DoNotEditCommentBase,
    output: MarkdownOutput,
    writeCoreNode: ParamWriteCoreNode,
): void {
    writeDeepCoreNode(
        BlockQuoteNode({
            children: [
                PlainTextNode({
                    text:
                        'This file is automatically generated by a build script.',
                }),
                HtmlElementNode({ tagName: 'br' }),
                PlainTextNode({
                    text:
                        'If you notice anything off, please feel free to open a new issue!',
                }),
            ],
        }),
        output,
        writeCoreNode,
    );
}
