import { BlockQuoteNode } from '../../nodes/BlockQuote';
import { LineBreakNode } from '../../nodes/LineBreak';
import { PlainTextNode } from '../../nodes/PlainText';
import { MarkdownOutput } from './MarkdownOutput';
import { DoNotEditCommentBase } from './nodes/DoNotEditComment';
import { writeDeepRenderMarkdownNode, ParamWriteRenderMarkdownNode } from '.';

export function writeDoNotEditComment(
    _doNotEditComment: DoNotEditCommentBase,
    output: MarkdownOutput,
    writeRenderMarkdownNode: ParamWriteRenderMarkdownNode,
): void {
    writeDeepRenderMarkdownNode(
        BlockQuoteNode({
            children: [
                PlainTextNode({
                    text:
                        'This file is automatically generated by a build script.',
                }),
                LineBreakNode({}),
                PlainTextNode({
                    text:
                        'If you notice anything off, please feel free to open a new issue!',
                }),
            ],
        }),
        output,
        writeRenderMarkdownNode,
    );
}
