name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 11.x, 12.x, 13.x, 14.x]

        name: Node ${{ matrix.node-version }} lint, typecheck and style

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: |
                  npm install -g npm@latest
                  npm ci
            - name: Lint and style check
              run: npm run lint
            - name: Typecheck packages
              run: npm run typecheck

    test_on_primary_node_version:
        runs-on: ubuntu-latest

        name: Node 14.x tests

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: Install dependencies
              run: |
                  npm install -g npm@latest
                  npm ci
            - name: Test packages
              run: npm run test
            - name: Publish code coverage report
              uses: codecov/codecov-action@v1
              with:
                  flags: unittest
                  name: codecov

    test_on_other_node_versions:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 11.x, 12.x, 13.x]

        name: Node ${{ matrix.node-version }} tests

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: |
                  npm install -g npm@latest
                  npm ci
            - name: Test packages
              run: npm run test
